use crate::models::cleanup::{CleanableItem, CleanupCategory, CleanupScanResult};
use crate::platform::Platform;
use crate::analyzer::storage::get_dir_size;
use chrono::Local;
use bytesize::ByteSize;
use std::path::PathBuf;

pub fn scan_cleanable_items() -> CleanupScanResult {
    let mut items = Vec::new();
    let mut total_reclaimable_bytes = 0;
    let mut total_file_count = 0;

    // 1. User application caches
    let mut user_cache_paths = Vec::new();
    let mut user_cache_size = 0;
    let mut user_cache_files = 0;
    for dir in Platform::cache_directories() {
        let (s, f) = get_dir_size(&dir);
        user_cache_size += s;
        user_cache_files += f;
        user_cache_paths.push(dir.to_string_lossy().to_string());
    }
    if user_cache_size > 0 {
        items.push(CleanableItem {
            category: CleanupCategory::UserCache,
            display_name: CleanupCategory::UserCache.display_name().to_string(),
            description: "Temporary files created by apps to load faster. Safe to clear; apps will rebuild them.".to_string(),
            paths: user_cache_paths,
            total_size_bytes: user_cache_size,
            total_size_display: ByteSize(user_cache_size).to_string(),
            file_count: user_cache_files,
            safe_to_clean: true,
        });
        total_reclaimable_bytes += user_cache_size;
        total_file_count += user_cache_files;
    }

    // 2. Temp files
    let mut temp_paths = Vec::new();
    let mut temp_size = 0;
    let mut temp_files = 0;
    for dir in Platform::temp_directories() {
        let (s, f) = get_dir_size(&dir);
        temp_size += s;
        temp_files += f;
        temp_paths.push(dir.to_string_lossy().to_string());
    }
    if temp_size > 0 {
        items.push(CleanableItem {
            category: CleanupCategory::TempFiles,
            display_name: CleanupCategory::TempFiles.display_name().to_string(),
            description: "Caches and workspace junk written by installers, text editors, and compiler tools.".to_string(),
            paths: temp_paths,
            total_size_bytes: temp_size,
            total_size_display: ByteSize(temp_size).to_string(),
            file_count: temp_files,
            safe_to_clean: true,
        });
        total_reclaimable_bytes += temp_size;
        total_file_count += temp_files;
    }

    // 3. Browser caches
    let mut browser_paths = Vec::new();
    let mut browser_size = 0;
    let mut browser_files = 0;
    for dir in Platform::browser_cache_directories() {
        let (s, f) = get_dir_size(&dir);
        browser_size += s;
        browser_files += f;
        browser_paths.push(dir.to_string_lossy().to_string());
    }
    if browser_size > 0 {
        items.push(CleanableItem {
            category: CleanupCategory::BrowserCache,
            display_name: CleanupCategory::BrowserCache.display_name().to_string(),
            description: "Cached website resources like images, styles, and scripts. Clearing frees up space but may slightly slow initial page loads next time.".to_string(),
            paths: browser_paths,
            total_size_bytes: browser_size,
            total_size_display: ByteSize(browser_size).to_string(),
            file_count: browser_files,
            safe_to_clean: true,
        });
        total_reclaimable_bytes += browser_size;
        total_file_count += browser_files;
    }

    // 4. Logs
    let mut log_paths = Vec::new();
    let mut log_size = 0;
    let mut log_files = 0;
    for dir in Platform::log_directories() {
        let (s, f) = get_dir_size(&dir);
        log_size += s;
        log_files += f;
        log_paths.push(dir.to_string_lossy().to_string());
    }
    if log_size > 0 {
        items.push(CleanableItem {
            category: CleanupCategory::Logs,
            display_name: CleanupCategory::Logs.display_name().to_string(),
            description: "System history logs and background diagnostics logs generated by services and running apps.".to_string(),
            paths: log_paths,
            total_size_bytes: log_size,
            total_size_display: ByteSize(log_size).to_string(),
            file_count: log_files,
            safe_to_clean: true,
        });
        total_reclaimable_bytes += log_size;
        total_file_count += log_files;
    }

    // 5. Trash / Recycle Bin
    let mut trash_paths = Vec::new();
    let mut trash_size = 0;
    let mut trash_files = 0;
    
    let trash_dirs = get_trash_paths();
    for dir in trash_dirs {
        let (s, f) = get_dir_size(&dir);
        trash_size += s;
        trash_files += f;
        trash_paths.push(dir.to_string_lossy().to_string());
    }
    if trash_size > 0 {
        items.push(CleanableItem {
            category: CleanupCategory::Trash,
            display_name: CleanupCategory::Trash.display_name().to_string(),
            description: "Files you deleted that are waiting in the Trash/Recycle Bin.".to_string(),
            paths: trash_paths,
            total_size_bytes: trash_size,
            total_size_display: ByteSize(trash_size).to_string(),
            file_count: trash_files,
            safe_to_clean: true,
        });
        total_reclaimable_bytes += trash_size;
        total_file_count += trash_files;
    }

    // 6. Old downloads (flag directories over 90 days - optional, but let's add it for completeness)
    if let Some(home) = dirs::home_dir() {
        let downloads = home.join("Downloads");
        if downloads.exists() {
            let (s, f) = get_dir_size(&downloads);
            if s > 0 {
                items.push(CleanableItem {
                    category: CleanupCategory::Downloads,
                    display_name: CleanupCategory::Downloads.display_name().to_string(),
                    description: "Files inside your Downloads folder. These are highlighted for manual review; we will NOT delete them automatically.".to_string(),
                    paths: vec![downloads.to_string_lossy().to_string()],
                    total_size_bytes: s,
                    total_size_display: ByteSize(s).to_string(),
                    file_count: f,
                    safe_to_clean: false, // User review required
                });
            }
        }
    }

    CleanupScanResult {
        items,
        total_reclaimable_bytes,
        total_reclaimable_display: ByteSize(total_reclaimable_bytes).to_string(),
        total_file_count,
        scanned_at: Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
    }
}

fn get_trash_paths() -> Vec<PathBuf> {
    let mut paths = Vec::new();
    #[cfg(target_os = "macos")]
    {
        if let Some(home) = dirs::home_dir() {
            paths.push(home.join(".Trash"));
        }
    }
    #[cfg(target_os = "windows")]
    {
        paths.push(PathBuf::from(r"C:\$Recycle.Bin"));
    }
    paths
}
